/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on Aug 22, 2011, 6:08:53 PM
 */
package regex;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author mihnea
 */
public class GUI extends javax.swing.JFrame {

    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgMetode = new javax.swing.ButtonGroup();
        fieldRegex = new javax.swing.JTextField();
        labelRegex = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cMultiline = new javax.swing.JCheckBox();
        cCase = new javax.swing.JCheckBox();
        cDotAll = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        rMatches = new javax.swing.JRadioButton();
        rLookingAt = new javax.swing.JRadioButton();
        rFind = new javax.swing.JRadioButton();
        bAplica = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInput = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        fieldRegex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRegexActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(fieldRegex, gridBagConstraints);

        labelRegex.setText("Regex");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(labelRegex, gridBagConstraints);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        cMultiline.setText("MULTILINE");
        cMultiline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMultilineActionPerformed(evt);
            }
        });

        cCase.setText("CASE_INSENSITIVE");

        cDotAll.setText("DOTALL");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(cMultiline)
                    .add(cCase)
                    .add(cDotAll))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(cMultiline)
                .add(18, 18, 18)
                .add(cCase)
                .add(18, 18, 18)
                .add(cDotAll)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Methods"));

        bgMetode.add(rMatches);
        rMatches.setText("matches");

        bgMetode.add(rLookingAt);
        rLookingAt.setText("lookingAt");

        bgMetode.add(rFind);
        rFind.setText("find");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(rMatches)
                    .add(rLookingAt)
                    .add(rFind))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(rMatches)
                .add(18, 18, 18)
                .add(rLookingAt)
                .add(18, 18, 18)
                .add(rFind)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel2, gridBagConstraints);

        bAplica.setText("Do it!");
        bAplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAplicaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(bAplica, gridBagConstraints);

        jSplitPane1.setResizeWeight(0.5);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        taInput.setColumns(20);
        taInput.setRows(5);
        jScrollPane1.setViewportView(taInput);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jScrollPane1, gridBagConstraints);

        jSplitPane1.setLeftComponent(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        taOutput.setColumns(20);
        taOutput.setEditable(false);
        taOutput.setRows(5);
        jScrollPane2.setViewportView(taOutput);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jScrollPane2, gridBagConstraints);

        jSplitPane1.setRightComponent(jPanel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jSplitPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldRegexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRegexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRegexActionPerformed

    private void cMultilineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMultilineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cMultilineActionPerformed

    private void bAplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAplicaActionPerformed

        if (fieldRegex.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "No regex.", "Error", JOptionPane.ERROR_MESSAGE);;
            return;
        }

        if (taInput.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "No input.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String out = "";

        int opts = 0;
        if (cMultiline.isSelected())
            opts |= Pattern.MULTILINE;
        if (cCase.isSelected())
            opts |= Pattern.CASE_INSENSITIVE;
        if (cDotAll.isSelected())
            opts |= Pattern.DOTALL;
        
        Pattern p = null;
        try {
            p = Pattern.compile(fieldRegex.getText().trim(), opts);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Wrong regex", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
        if (p != null) {
            Matcher m  = p.matcher(taInput.getText());

            if (rMatches.isSelected()) {
                if (m.matches())
                    out = "Matches: true";
                else
                    out = "Matches: false";
            }

            else if (rLookingAt.isSelected()) {
                if (m.lookingAt())
                    out = "LookingAt: true";
                else
                    out = "LookingAt: false";
            }

            else if (rFind.isSelected()) {
                int i;
                int n;
                int count = 0;
                out = "";
                
                
                while(m.find()) {
                    ++count;
                    if (m.group().equals(""))
                        continue;
                    n = m.groupCount();
                    out += "Match: " + m.group() + "\n";
                    for (i = 1; i <= n; ++i) {
                        out += i + ": " + m.group(i);
                        out += "\n";
                    }
                    out += "\n";
                }
                if (count == 0)
                    out = "Nothing found.";
            }

            else {
                out = "";
                JOptionPane.showMessageDialog(this, "No method chosen.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            taOutput.setText(out);
        }
    }//GEN-LAST:event_bAplicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAplica;
    private javax.swing.ButtonGroup bgMetode;
    private javax.swing.JCheckBox cCase;
    private javax.swing.JCheckBox cDotAll;
    private javax.swing.JCheckBox cMultiline;
    private javax.swing.JTextField fieldRegex;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelRegex;
    private javax.swing.JRadioButton rFind;
    private javax.swing.JRadioButton rLookingAt;
    private javax.swing.JRadioButton rMatches;
    private javax.swing.JTextArea taInput;
    private javax.swing.JTextArea taOutput;
    // End of variables declaration//GEN-END:variables
}
